In [1]:
# 1.Install TensorFlow using pip
pip install tensorflow numpy

  Using cached tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
  Using cached absl_py-2.5.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached grpcio-1.83.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
  Using cached keras-3.15.1-py3-none-any.whl.metadata (6.4 kB)
  Using cached h5py-3.14.0-cp313-cp313-win_amd64.whl.metadata (2.7 kB)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Using cached tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
Using cached grpcio-1.83.0-cp313-cp313-win_amd64.whl (5.2 MB)
Using cached h5py-3.14.0-cp313-cp313-win_amd


[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# 2 & 3. Verify TensorFlow Installation and Display Version
import tensorflow as tf
import numpy as np

# Verify installation and print version
print("TensorFlow Version:", tf.__version__)
print("NumPy Version:", np.__version__)
print("GPU Available:", len(tf.config.list_physical_devices('GPU')) > 0)

TensorFlow Version: 2.21.0
NumPy Version: 2.2.4
GPU Available: False


In [3]:
#4. Scalar Tensor (0-D Tensor)
scalar_tensor = tf.constant(42)
print("Scalar Tensor:\n", scalar_tensor)
print("Shape:", scalar_tensor.shape, "| Dimensions:", scalar_tensor.ndim)

Scalar Tensor:
 tf.Tensor(42, shape=(), dtype=int32)
Shape: () | Dimensions: 0


In [4]:
#5. Vector Tensor (1-D Tensor)
vector_tensor = tf.constant([10.0, 20.0, 30.0])
print("Vector Tensor:\n", vector_tensor)
print("Shape:", vector_tensor.shape, "| Dimensions:", vector_tensor.ndim)

Vector Tensor:
 tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
Shape: (3,) | Dimensions: 1


In [5]:
#6. Matrix Tensor (2-D Tensor)
matrix_tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
print("Matrix Tensor:\n", matrix_tensor)
print("Shape:", matrix_tensor.shape, "| Dimensions:", matrix_tensor.ndim)

Matrix Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3) | Dimensions: 2


In [6]:
#7. Three-Dimensional Tensor (3-D Tensor)
tensor_3d = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("3D Tensor:\n", tensor_3d)
print("Shape:", tensor_3d.shape, "| Dimensions:", tensor_3d.ndim)

3D Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Shape: (2, 2, 2) | Dimensions: 3


In [7]:
#8 & 9. Tensor Addition and Subtraction
a = tf.constant([[2.0, 4.0], [6.0, 8.0]])
b = tf.constant([[1.0, 1.0], [2.0, 3.0]])

# Addition
tensor_add = tf.add(a, b)
# Subtraction
tensor_sub = tf.subtract(a, b)

print("Tensor Addition:\n", tensor_add)
print("Tensor Subtraction:\n", tensor_sub)

Tensor Addition:
 tf.Tensor(
[[ 3.  5.]
 [ 8. 11.]], shape=(2, 2), dtype=float32)
Tensor Subtraction:
 tf.Tensor(
[[1. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32)


In [8]:
#10 & 11. Element-wise Multiplication and Matrix Multiplication
x = tf.constant([[1, 2], [3, 4]])
y = tf.constant([[5, 6], [7, 8]])

# Element-wise multiplication
elem_mult = tf.multiply(x, y)

# Matrix multiplication (Dot product)
matmul_res = tf.matmul(x, y)

print("Element-wise Multiplication:\n", elem_mult)
print("Matrix Multiplication (Matmul):\n", matmul_res)

Element-wise Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Matrix Multiplication (Matmul):
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [9]:
#12. Reshaping an Existing Tensor
flat_tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape from (12,) to (3, 4) and (2, 2, 3)
reshaped_2d = tf.reshape(flat_tensor, shape=(3, 4))
reshaped_3d = tf.reshape(flat_tensor, shape=(2, 2, 3))

print("Original Shape:", flat_tensor.shape)
print("Reshaped (3, 4):\n", reshaped_2d)
print("Reshaped (2, 2, 3):\n", reshaped_3d)

Original Shape: (12,)
Reshaped (3, 4):
 tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
Reshaped (2, 2, 3):
 tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [10]:
#13. NumPy to Tensor Conversion
# Create a NumPy array
np_array = np.array([[10, 20], [30, 40]], dtype=np.float32)

# Convert to TensorFlow Tensor
converted_tensor = tf.convert_to_tensor(np_array)

# Convert back to NumPy array
back_to_numpy = converted_tensor.numpy()

print("Original NumPy Array:\n", np_array)
print("Converted tf.Tensor:\n", converted_tensor)
print("Back to NumPy:\n", back_to_numpy)

Original NumPy Array:
 [[10. 20.]
 [30. 40.]]
Converted tf.Tensor:
 tf.Tensor(
[[10. 20.]
 [30. 40.]], shape=(2, 2), dtype=float32)
Back to NumPy:
 [[10. 20.]
 [30. 40.]]
